"use client"

export default function About () {

    return (
        <main className="text-pg">
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>\
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>

    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
     <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>\
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>

    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    <div>
        dpgvfoknvoksdhnjfndsojklfbvnajdsbfjkbadsfjbjfbjasbjfabonaofnldsanfjndskfgkds
        dlmsfvjdsnofnblsdngls
        dslkdsnjklngldsng
        fdldsaokfnoknopn
    </div>
    
    </main>
)}